all:tcp_server6-1 tcp_server6-2 tcp_server6-3 tcp_server6-4 tcp_client6-1 tcp_client6-2 tcp_client6-3 tcp_client6-4 

tcp_server6-1:
	g++ -o tcp_server6-1 tcp_server6-1.cpp

tcp_server6-2:
	g++ -o tcp_server6-2 tcp_server6-2.cpp

tcp_server6-3:
	g++ -o tcp_server6-3 tcp_server6-3.cpp

tcp_server6-4:
	g++ -o tcp_server6-4 tcp_server6-4.cpp

tcp_client6-1:
	g++ -o tcp_client6-1 tcp_client6-1.cpp

tcp_client6-2:
	g++ -o tcp_client6-2 tcp_client6-2.cpp

tcp_client6-3:
	g++ -o tcp_client6-3 tcp_client6-3.cpp

tcp_client6-4:
	g++ -o tcp_client6-4 tcp_client6-4.cpp

clean:
	rm tcp_server6-1
	rm tcp_server6-2
	rm tcp_server6-3
	rm tcp_server6-4
	rm tcp_client6-1
	rm tcp_client6-2
	rm tcp_client6-3
	rm tcp_client6-4

