all:tcp_server5-1 tcp_server5-2 tcp_server5-3 tcp_client5-1 tcp_client5-2 tcp_client5-3

tcp_server5-1:
	g++ -o tcp_server5-1 tcp_server5-1.cpp

tcp_server5-2:
	g++ -o tcp_server5-2 tcp_server5-2.cpp

tcp_server5-3:
	g++ -o tcp_server5-3 tcp_server5-3.cpp

tcp_client5-1:
	g++ -o tcp_client5-1 tcp_client5-1.cpp

tcp_client5-2:
	g++ -o tcp_client5-2 tcp_client5-2.cpp

tcp_client5-3:
	g++ -o tcp_client5-3 tcp_client5-3.cpp

clean: 
	rm tcp_server5-1
	rm tcp_server5-2
	rm tcp_server5-3
	rm tcp_client5-1
	rm tcp_client5-2
	rm tcp_client5-3
