all:tcp_server4-1 tcp_server4-2 tcp_client4-1-1 tcp_client4-1-2 tcp_client4-2-1 tcp_client4-2-2

tcp_server4-1:
	g++ -o tcp_server4-1 tcp_server4-1.cpp

tcp_server4-2:
	g++ -o tcp_server4-2 tcp_server4-2.cpp

tcp_client4-1-1:
	g++ -o tcp_client4-1-1 tcp_client4-1-1.cpp

tcp_client4-1-2:
	g++ -o tcp_client4-1-2 tcp_client4-1-2.cpp

tcp_client4-2-1:
	g++ -o tcp_client4-2-1 tcp_client4-2-1.cpp

tcp_client4-2-2:
	g++ -o tcp_client4-2-2 tcp_client4-2-2.cpp

clean: 
	rm tcp_server4-1 
	rm tcp_server4-2 
	rm tcp_client4-1-1 
	rm tcp_client4-1-2 
	rm tcp_client4-2-1 
	rm tcp_client4-2-2 
